# Generated by Django 3.2.8 on 2022-04-27 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220427_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='refund_granted',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='refund_requested',
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
