# Generated by Django 3.2.8 on 2022-04-27 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220427_1058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
