# Generated by Django 3.2.8 on 2022-04-27 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='ssl_charge_id',
        ),
    ]
